(function() {
var f=!0,k=null,l=!1;function m(){return(new Date).getTime()}var aa=m(),n=window,q=n.setTimeout,ba=n.XMLHttpRequest,ca=n.ActiveXObject,r=n.parent,s={version:"6203"};"undefined"==typeof n.dT_&&(document.dT_=window.dT_,n.dT_=s);function da(){return ba?new ba:new ca("MSXML2.XMLHTTP.3.0")}
function t(a){var b,c,d,e=document.cookie.split(";");for(b=0;b<e.length;b++)if(c=e[b].indexOf("\x3d"),d=e[b].substring(0,c),c=e[b].substring(c+1),d=d.replace(/^\s+|\s+$/g,""),d==a)return"DTSA"==a.toUpperCase()?decodeURIComponent(c):c;return k}function ea(a){document.cookie=a+'\x3d"";path\x3d/'+(u.domain?";domain\x3d"+u.domain:"")+"; expires\x3dThu, 01-Jan-70 00:00:01 GMT;"}
function v(a,b){b?(b="DTSA"==a.toUpperCase()?w(b):b,document.cookie=a+"\x3d"+b+";path\x3d/"+(u.domain?";domain\x3d"+u.domain:"")):ea(a)}function x(a,b){for(var c=1;c<arguments.length;c++)a.push(arguments[c])}s.dC=ea;s.sC=v;s.gC=t;s.gx=da;s.st=function(a,b){return q(a,b)};s.nw=m;var y=[],z=navigator.userAgent;
try{var fa=/Firefox[\/\s](\d+\.\d+)/,ga=/(iPod|iPhone|iPad)/,ha=/AppleWebKit/;if(0<=z.indexOf("MSIE"))y.ie=~~z.substr(z.lastIndexOf("MSIE")+5,3);else if(0<=z.indexOf("Trident"))0<=z.indexOf("rv:")?y.ie=~~z.substr(z.lastIndexOf("rv:")+3,2):0<=z.indexOf("rv ")&&(y.ie=~~z.substr(z.lastIndexOf("rv ")+3,2));else if(0<=z.indexOf("Android"))y.ab=parseFloat(z.substr(z.indexOf("Android")+8,1));else if(z.match(ga)&&z.match(ha))y.msf=parseFloat(z.match(/Version\/([0-9]*\.[0-9]*)/)[1]);else if(("Safari"==navigator.appName||
-1<z.indexOf("Safari"))&&-1==z.indexOf("Chrom"))y.sf=~~z.substr(z.lastIndexOf("Version/")+8,1);else if(n.opera)y.op=~~n.opera.version().split(".")[0];else if(fa.test(z)){var ia=~~z.match(fa)[1];y.ff=-1==ia?0:ia}else{var ja=z.indexOf("Chrom");-1<ja&&(y.ch=~~z.substring(ja+7,ja+9))}}catch(ka){}s.gBI=function(){return y};var u={reportUrl:"dynaTraceMonitor",m:""};function la(a){return!a||1!=a.length||void 0===u.t?l:-1!=u.t.indexOf(a)}var ma=document.getElementsByTagName("script");
if(0<ma.length)for(var na,oa=ma.length-1;0<=oa;oa--)if(na=ma[oa],0<=na.src.search("dtagent")&&na.attributes){var pa=na.attributes.getNamedItem("data-dtconfig");if(pa&&pa.value){var qa=na.src,ra=pa.value;if(qa){var sa=/dtagent(dbg){0,1}[0-9]{2}_[a-zA-Z_0-9]*_[0-9]{4}/.exec(qa);sa&&(u.t=sa[0].split("_")[1])}if(ra)for(var ta=ra.split("|"),A=0;A<ta.length;A++){var ua=ta[A].indexOf("\x3d");-1==ua?u[ta[A]]=f:u[ta[A].substring(0,ua)]=ta[A].substring(ua+1,ta[A].length)}}break}
s.smbi=function(a){if(la(a)&&-1==u.m.indexOf(a))return u.m+=a,f;la(a)&&n.console&&n.console.log("WARNING: "+('Module "'+a+'" already enabled!'));return l};s.isc=function(a){return a&&382<=a};s.cfg=function(a){return u[a]};s.ism=la;var va="\t\n\r";function wa(a){return a?String.trim?a.trim():a.replace(/^\s+|\s+$/g,""):k}function xa(a,b){for(var c=a.length;c--;)if(a[c]===b)return f;return l}var ya=[];
function B(a,b,c){a.addEventListener?a.addEventListener(b,c,f):a.attachEvent&&a.attachEvent("on"+b,c);x(ya,{object:a,event:b,F:c})}function za(a){try{var b=a.tagUrn;if(b&&-1!=b.indexOf("schemas-microsoft-com:vml"))return f}catch(c){return f}return l}function Aa(a){var b=0;if(a)for(var c=a.length,d=0;d<c;d++)b=31*b+a.charCodeAt(d),b&=b;return b}function Ba(a,b){if(n.sessionStorage)try{n.sessionStorage[a]=b;return}catch(c){}v(a,b)}function Ca(a){return n.sessionStorage?n.sessionStorage[a]:t(a)}
var Da={"!":"%21","~":"%7E","*":"%2A","(":"%28",")":"%29","'":"%27",$:"%24",";":"%3B",",":"%2C"},Ea={"^":"^^","|":"^p",",":"^c",";":"^s"};function w(a){a=encodeURIComponent(a);var b=[];if(a)for(var c=0;c<a.length;c++){var d=a.charAt(c),e=Da[d];e?x(b,e):x(b,d)}return b.join("")}function C(a){var b=[];if(a)for(var c=0;c<a.length;c++){var d=a.charAt(c),e=Ea[d];e?x(b,e):x(b,d)}return b.join("")}
function Fa(a){if(a){for(var b=[],c=0;c<a.length;c++){var d=a.charAt(c),e=u.spc;e||(e="");e+=va;-1==e.indexOf(d)&&x(b,d)}a=b.join("")}return a}function Ga(){var a=document.location.href,b=a.indexOf("#");0<=b&&(a=a.substr(0,b));return a}function Ha(a){var b=t("dtLatC"),c=0,d=[],e=0;if(b&&0<b.length){b=b.split("|");1<b.length&&(e=b.length-1);9<e&&(e=9);for(var h=1;h<=e;h++)c+=parseFloat(b[h]),d[h+1]=b[h]}e++;d[0]=~~((c+a)/e);d[1]=a;v("dtLatC",d.join("|"));return d[0]}
function Ia(){return"undefined"!=typeof n.performance&&n.performance.timing&&(!y.ff||9<y.ff)?n.performance:k}var Ja={};function Ka(a,b,c,d){if(Object.defineProperty&&(!y.ie||8<y.ie))Ja[b]=a[b],Object.defineProperty(a,b,{get:function(){return c?c.apply(a,k):Ja[b]},set:function(c){Ja[b]=c;d&&d.apply(a,[c]);return Ja[b]},configurable:f})}function La(a,b){if(a[b]&&Object.defineProperty&&(!y.ie||8<y.ie)){var c=a[b];delete a[b];Ja[b]=k;a[b]=c}}s.ael=B;s.lv=Ca;s.sv=Ba;
s.gh=function(a){return-1==a.indexOf("://")?k:a.split("/")[2].split(":")[0].toLowerCase()};s.cvs=function(a,b,c,d){if(u.ffi)return f;d||(d="");for(var e=l,h=l,g=l,p=0;p<a.length&&(!e||!h);)a[p]=a[p].split("."),e=a[p][0]==b?f:l,h=a[p][1]==c?f:l,!g&&e&&(g=f),p++;if(e&&h)return f;if(g)return Ma(d+" version ("+b+"."+c+") official not supported"),f;Ma(d+" not instrumented because version ("+b+"."+c+") not supported");return l};s.esc=w;s.aesc=C;s.ulc=Ha;s.gP=Ia;s.apl=Ka;s.rpl=La;
s.dbg=function(a){v("dtUseDebugAgent",a)};s.dbc=function(a){v("dt_dbg_console",a)};var Na=6E8,Oa="dtPC",D=m()%Na+"_"+~~(1E3*Math.random());s.b=D;function Pa(){var a=t(Oa),b=[];if(a&&"-"!=a)for(var a=a.split("|"),c=0;c<a.length;c++){var d=a[c].split("#");if(2==d.length&&d[0]&&d[1]){var e=d[0],h=~~e.split("_")[0],g=m()%Na;g<h&&(g+=Na);h+9E5>g&&x(b,{b:e,l:d[1]})}}return b}function Qa(){var a=Pa();if(0<a.length){for(var b=[],c=0;c<a.length;c++)a[c].b!=D&&x(b,a[c]);Ra(b)}}
function Ra(a){var b="";if(a){for(var b=[],c=0;c<a.length;c++)0<c&&x(b,"|"),x(b,a[c].b),x(b,"#"),x(b,a[c].l);b=b.join("")}b||(b="-");v(Oa,b)}s.gFId=function(){return D};s.gDtc=function(){var a=t("dtCookie");if(a){var b=a.indexOf("|");-1!=b&&(a=a.substring(0,b))}return a};s.gPAH=function(a){a=D+"#"+s.esc(a);var b=t(Oa);return b&&0<=b.indexOf(a)?k:a};var Sa=0,Ta=0,E=k,Ua=void 0,Va=u.wi,Wa=l;
function Xa(a){for(var b=0,c=document.getElementsByTagName("img"),d=0;d<c.length;d++)""!=c[d].src&&(b+=a(c[d]));c=document.getElementsByTagName("input");for(d=0;d<c.length;d++)"image"==c[d].type&&""!=c[d].src&&(b+=a(c[d]))}function Ya(){Xa(function(a){a.z=f})}function $a(a){Xa(ab);E||(E=[]);x(E,a);Ta===Sa&&bb()}function ab(a){a.z||(a.z=f,y.v&&a.complete||a.naturalWidth||(B(a,"load",cb),B(a,"error",cb),a.src=a.src,Sa++))}function cb(){Ta++;Ta===Sa&&bb()}
function bb(){if(E){for(var a=0;a<E.length;a++)E[a]();E=k}}Va&&(Ua="all"==Va,Wa=f);s.g=k;s.n=k;s.C=0;var db=k,eb,fb,gb={};try{r&&(r!=self&&r.dT_&&r.dT_.version==s.version)&&(fb=r.dT_,db=r.dT_.tdto())}catch(hb){}db?(s.g=db.g,s.n=db.n,eb=fb.b,fb.C++):(s.g=D,s.n=document.title);s.tp=function(){return!db};s.tdto=function(){try{if(r&&r!=self&&r.dT_)return r.dT_.tdto()}catch(a){}return s};s.aFU=function(a){a=C(a);gb[a]||(gb[a]="1")};s.iRO=function(a){return"1"==gb[a]};
function ib(a,b,c,d){for(var e=3,h=0;0<e;)try{var g=da(),h=m();a(g);g.open("POST",b,c);g.setRequestHeader("Content-Type","text/plain;charset\x3dUTF-8");g.send(d);e=0}catch(p){e--}return h}var F=k,jb=[],kb=l,lb=l,mb,nb=f,ob=l,pb,qb;function rb(){var a=this;a.f=[];a.a=function(b,c){x(a.f,[b,c])}}function sb(a){Ha(a/2)}function tb(a,b,c){ub(a,b,l);F&&vb(l,c)}
function ub(a,b,c){var d="";if(a)c=wb();else{var d="",e=G.length;b&&(H=[]);if(0<e){for(b=0;b<e;b++){var h=xb(G[b],f,c,l);h&&0<h.length&&(I&&"_load_"==G[b].type&&(d=I.B?"d|"+I.name+"|"+I.type+"|"+I.b+"|"+I.start+"|"+I.location+"|"+I.title:"s|"+I.name+"|"+I.type+"|"+I.b+"|"+I.start,I=k),0<d.length&&(d+=","),d+=h)}G=[];for(var g in H)H.hasOwnProperty(g)&&x(G,H[g])}c=d}d=c;F=k;0<d.length?(F=new rb,F.a("a",w(d)),F.a("fId",D),a&&F.a("PV",1),s.g!=D&&F.a("pId",s.g),eb&&F.a("pFId",eb),F.a("rId",u.rid),F.a("rpId",
u.rpid),a||(lb||F.a("title",w(Fa(document.title))),(c=yb())&&F.a("domR",c),lb=f),zb()&&F.a("unload","xhr"),Ab(a)):nb===l&&(F||(F=new rb),c=F.f.length,Ab(a),F.f.length>c?F.a("fId",D):F=k);nb=l}function Ab(a){for(var b=0;b<jb.length;b++)jb[b](F,a)}function Bb(){for(var a=[],b=0;b<F.f.length;b++)0<b&&x("$"),x(a,"$",F.f[b][0],"\x3d",F.f[b][1]);return a.join("")}function Cb(){var a=Bb(),b=y.ie?1500:7E3;u.msl&&(b=Math.min(b,~~u.msl));return 0===a.length%b?~~(a.length/b):~~(a.length/b)+1}
function vb(a,b){function c(a){a.onreadystatechange=function(){if(4==a.readyState){if(200==a.status){var b=m()-e;d&&d(b)}a=k}}}var d=sb,e=m();F.a("time",e);var h=Db(),g=Cb(),p=y,M=u.fsc,U;U=!a||a&&!(p.sf||p.op||p.ff&&(1<g||u.sffs||17<p.ff)||p.ie&&(9>p.ie||u.sies)||p.msf||p.ab||p.ch&&(22<p.ch||M));b&&(U=!b);p=1==g&&a&&(p.ie&&9>p.ie||p.ch&&!M);if(h!==k)if(g=u.reportUrl?u.reportUrl:"dynaTraceMonitor",p)U=document.createElement("img"),d&&(U.onerror=function(){d(m()-e)}),U.setAttribute("src",g+"?"+h[0]);
else if(p=g,M=h[0],u.spl)for(var Za=0;Za<h.length;Za++)M=k,p=g+"?"+h[Za],e=ib(c,p,U,M);else e=ib(c,p,U,M)}
function Db(){var a=Bb(),b=k;if(u.spl){var c=y.ie?1500:7E3;u.msl&&(c=Math.min(c,~~u.msl));var d=Cb(),e,h=m(),g=0;if(1<d){if(100>d)for(var b=[],p=0;p<d;p++){var M="sid\x3d"+h+"\x26p"+(p+1)+"_"+d+"\x3d";g+c<=a.length?(e=a.slice(g,g+c),"%"==e.charAt(e.length-1)&&a.length>=g+c+1&&(e+=a.charAt(g+c),e+=a.charAt(g+c+1),g+=2),"%"==e.charAt(e.length-2)&&a.length>=g+c+2&&(e+=a.charAt(g+c),g+=1)):e=a.slice(g);x(b,M+e);g+=c}}else b=[a]}else b=[a];return b}
function yb(){var a=Ia();if(a&&a.timing){if(a.timing.domComplete&&0<a.timing.domComplete)return a.timing.domComplete;if(a.timing.s&&0<a.timing.s)return a.timing.s}return mb}function Eb(a){kb&&m()+a<qb&&(clearTimeout(pb),kb=l);kb||(qb=m()+(a?a:0),pb=q(Fb,void 0!=a?a:0),kb=f)}function Fb(){kb=l;tb(l,l,l)}s.ss=function(a,b,c){tb(b,c,a)};s.asl=function(a){x(jb,a)};s.sMPS=function(a){Eb(a)};var J=k,G=[],H=[],Gb=[],Hb=0,K=[],L=[],Ib=u.wi,N;s.u=Jb;var Kb=[];
function O(){for(var a=0;a<Kb.length;a++)Kb[a]()}function Jb(){return H}function Lb(a,b,c,d,e,h){var g={start:c,stop:d,type:a,name:b,i:e,next:[],e:k,p:k,w:k,o:k,d:k,count:k,q:h?~~(2147483647*Math.random())+1:0,add:function(a){a&&a.name&&x(g.next,a)}};Gb[g.name]?(Gb[g.name]++,g.d=g.name,g.count=Gb[g.name],g.name+="#"+g.count):Gb[g.name]=1;return g}
function Mb(){var a=l,b=[],c;for(c in H)if(H.hasOwnProperty(c)){var d=H[c];0<d.p&&(m()>d.e&&(d.e+=6E4,x(b,d)),a=f)}0<b.length&&tb(f,f,l);for(c=0;c<b.length;c++)b[c].p--;a&&q(Mb,1E3)}function Nb(a,b){if(a)for(var c=k,d=0;d<a.length;d++){c=a[d];if(c.name==b||c.d&&c.d==b)return c;if(c.next&&(c=Nb(c.next,b),c!==k))return c}return k}function Ob(a){var b=k;G&&(b=Nb(G,a));return b}
function Pb(a,b,c,d,e){c||(c=m());a=Lb(b,a,c,k,k,e);"boolean"==typeof d&&d&&(d=J);if(d){if(b=k,b="string"==typeof d?Ob(d):"object"==typeof d?d:J){b.add(a);Qb(a);for(var h in H)H.hasOwnProperty(h)&&(H[h]&&H[h].e>a.start+1E4)&&(H[h].e=a.start+1E4)}}else Qb(a),Rb(a),x(H,a),J=a,x(G,a),a.e=a.start+1E4,a.p=100,q(Mb,5E3);return a}function Qb(a){if(J!=a)if(J=a){a=a.name;for(var b=Pa(),c=l,d=0;d<b.length;d++)b[d].b==D&&(b[d].l=w(a),c=f);c||x(b,{b:D,l:w(a)});Ra(b)}else Qa()}
function P(a,b,c){b||(b=m());var d=[];if(G)for(var e=0;e<G.length;e++)d[e]=Sb(G[e],a,b,c);a=l;for(b=0;b<G.length;b++)if(d[b])a=d[b];else{Q=k;c=[];for(var h in H)if(H.hasOwnProperty(h))if(e=H[h],e.name===G[b].name&&e.type===G[b].type)x(c,h);else if(N){var g=fb.u();e.w=r&&g[g.length-1]==N?"S":"A";N=k}for(e=0;e<c.length;e++){var g=c[e],p=H;p.splice(g,g-(g||NaN)+1||p.length)}}Eb(0);Qb(a)}
function Sb(a,b,c,d){var e;a.d&&a.d==b||a.name==b?(a.stop=c,d&&(a.start=d),a.i=document.getElementsByTagName("*").length):a.stop||(e=a);if(a.next&&0<a.next.length)for(var h=1;h<=a.next.length;h++){var g=Sb(a.next[a.next.length-h],b,c,d);g&&(e=g)}return e}function xb(a,b,c,d){if(a.o){var e=[],h=["0"];h[1]=a.o;h[2]=a.w;e[0]=h.join("|");e[1]=Tb(a,1,b,c,d);return e.join(",")}return Tb(a,1,b,c,d)}
function Tb(a,b,c,d,e){a.i||(a.i=document.getElementsByTagName("*").length);var h=[];if(a.next&&0<a.next.length){for(var g=0;g<a.next.length;g++){var p=Tb(a.next[g],b+1,c,d,e);if(p)h.push(p);else return k}c&&(c=a.next[a.next.length-1],c.stop?a.stop&&c.stop>a.stop&&(a.stop=c.stop):a.stop=void 0)}if(!d&&!e&&(!a.stop||0==a.stop))return k;d=[];d[0]=b.toString();d[1]=C(a.d?a.d:a.name);d[2]=a.count?a.count:"-";d[3]=C(a.type);d[4]=a.start;d[5]=a.stop?a.stop:0;d[6]=a.i;1==b&&a.h&&(d[7]=a.h);a.q&&(d[7]||(d[7]=
"-"),d[8]=a.q);h.unshift(d.join("|"));return 1<h.length?h.join(","):h[0]}function wb(){var a="",b=0,c=l,d=["_warning_","_error_","_log_","_rv_","_rs_"],e=~~(u.oat||180),h=~~(u.moa||30),g;for(g in H)if(H.hasOwnProperty(g)){var p=H[g];m()-p.start>1E3*e?q(function(a){return function(){P(a)}}(p.name),0):b+1>h&&!xa(d,p.type)?c||(Ma("Maximum open actions exceeded configured amount of "+(u.moa||30)+", dropping action "+p.name),c=f):(a=a?a+",":a,a+=xb(H[g],l,l,f),b++)}return a}
function zb(){if(0<Hb){var a=K.length;if(0<a)return K[a-1]}return k}function Ub(a,b,c){var d=k;1==arguments.length&&(b=3);var e=Vb(),h=k;e&&e.r&&(h=e.r);h||(h=zb());h?d=Wb(h):e?3<=b&&(d=Xb(e.getName(),e.type,e.start,k,c),e.r=d,Ib&&Ya()):J?1<=b&&(d=Wb(J.name,a,"xhr",m(),c),Ib&&Ya()):u.cux&&(d=Xb("Unlinked XHR","xhr",m(),k,c));return d}function Xb(a,b,c,d,e){a=Pb(a,b,c,d,e);a.k=1;L[a.name]=a;return a.name}function Wb(a,b,c,d,e){a=L[a];var h;a?(a.k++,h=a.name):J&&(h=Xb(b,c,d,J.name,e));return h}
function Yb(a){var b=0;if(b=L[a])b.k--,b=b.k,0>=b&&(P(a),L[a]=k,delete L[a])}function Zb(){var a=0,b;for(b in L)if(b&&L.hasOwnProperty(b))try{a+=L[b].k}catch(c){}return a}function Rb(a){N=k;if(fb){var b=fb.u();if(N=b[b.length-1])a.o=N.name,N.h?N.h++:N.h=1}}function R(a,b,c){var d=m();a=Fa(a);b=Lb(b,a,d,d,-1);$b(b,c)&&Eb(5E3)}function $b(a,b){var c;if(c=b?Ob(b):J)return c.add(a),l;Rb(a);x(G,a);return f}function Ma(a,b){R(a,"_warning_",b)}
s.ea=function(a,b,c,d){if(4>arguments.length||"undefined"==typeof d)d=f;return Pb(a,b,c,d).name};s.la=function(a,b,c){O();Wa&&Ua?$a(function(){P(a,b,c)}):P(a,b,c)};s.lx=function(a){if(1<Zb())q(function(){Yb(a)},0);else return Ib?$a(function(){q(function(){Yb(a)},0)}):q(function(){Yb(a)},0),O(),f;return l};s.ex=Ub;s.ec=function(a){a&&(x(K,a),Hb++)};s.lc=function(a){a&&(Hb--,q(function(){for(var b=-1,c=K.length-1;-1==b&&0<=c;)K[c]==a&&(b=c),c--; -1!=b&&(b==K.length-1?K.pop():K.splice(b,1))},0))};
s.pcn=R;s.pe=function(a,b){R(a,"_error_",b)};s.pw=Ma;s.pl=function(a,b){R(a,"_log_",b)};s.ewa=function(a){a=Ub(a,3,f);return Ob(a)};s.gWRI=function(a){return a.q};s.gAN=function(a){return a.name};s.rv=function(a,b){var c=m(),c=Lb("_rv_",a+"\x3d"+b,c,c,0);$b(c);Eb(5E3)};s.rs=function(a,b){var c=m(),c=Lb("_rs_",a+"\x3d"+b,c,c,0);$b(c);Eb(5E3)};s.ca=function(){return J};s.noa=function(){return!J||0<J.stop};s.ti=O;var ac,bc=l,cc=u.mepp;!cc&&0!=cc&&(cc=10);var dc=0;
function ec(a){dc++;dc<=cc&&(11>y.ie?R(n.event.type+":"+n.event.errorUrl+"["+n.event.errorLine+"] Code: "+n.event.errorCode+": "+n.event.errorMessage,"_error_"):R(a.type+":"+a.filename+"["+a.lineno+":"+a.colno+"] "+a.message,"_error_"))}
function fc(a,b,c){var d=l;if(!bc){bc=f;ac&&(ac!=fc&&"function"==typeof ac)&&(d=ac(a,b,c));var e=k;try{if(e="object"==typeof a?a.srcElement?a.srcElement.outerHTML&&200>a.srcElement.outerHTML.length?document.URL.split("#")[0]+"[-]: Error at '"+a.srcElement.outerHTML+"'":document.URL.split("#")[0]+"[-]: Error at tag: '"+a.srcElement.tagName+"'":"unknown error":"undefined"===typeof b||"undefined"==b?a:b+"["+c+"]: "+a){var h=Vb();h&&(e+=", user action: "+h.getName());dc++;dc<=cc&&!d&&R(e,"_error_")}}catch(g){}bc=
l}return d}y.ie?B(n,"error",ec):n.onerror!=fc&&(n.onerror&&(ac=n.onerror),n.onerror=fc);try{y.ie||Ka(window,"onerror",function(){return fc},function(a){ac=a})}catch(gc){}B(n,"unload",function(){La(window,"onerror");n.onerror=k});var hc="BUTTON",ic="INPUT",jc="HIDDEN",kc="SUBMIT",lc="RESET",mc="IMAGE",nc="IMG",oc="A",pc="FORM",qc="#DOCUMENT",rc="HTML",sc="BODY",tc="HEAD",uc="SELECT",vc="unknown",xc=wc(n.location.href),yc=0,zc=1,Ac=2,Bc=3,Cc=4,Dc=0;
function Ec(a){if(a)for(var b=document.getElementsByTagName("LABEL"),c=0;c<b.length;c++)if(b[c].htmlFor==a)return a=b[c],S(a.innerText,a.textContent);return k}function S(a){for(var b=0;b<arguments.length;b++){var c=arguments[b];if(c&&wa(c))return wa(c)}return k}function Fc(a){return a&&(a=a.split("/"),0<a.length)?a[a.length-1].split(".")[0]:k}function wc(a){if(a){var b=a.split("/");if(0<b.length&&(b=wa(b[b.length-1]),b!==k))return b}return a}
function Gc(a,b){if(!b||0>=b.length||20<Dc)return k;for(var c=0;c<b.length;c++){var d=b[c];if(y.ie&&za(d))return"VML Node";var e=d.nodeName?d.nodeName.toUpperCase():vc,h=d.type?d.type.toUpperCase():k,g=k;Dc++;if(g=Gc(a,d.childNodes))return g;Dc--;switch(a){case yc:e==ic&&h!=jc&&(e=h&&(h==hc||h==kc||h==lc||h==mc)?d.value:k,g=Ec(d.id),g=h&&(h==hc||h==kc||h==lc)?S(e,g):S(g,e));g||(g=S(d.textContent,d.innerText));break;case zc:if(e==ic&&h!=jc||e==hc)g=S(d.name,d.title,h&&h==mc?d.alt:k);break;case Ac:e==
ic&&h==mc?g=Fc(d.src):e==oc?g=S(d.title,wc(d.href)):e==nc?g=S(d.name,d.title,d.alt,Fc(d.src)):e==pc&&(g=S(d.name,d.id,d.action));g||(g=S(d.title,d.data,d.wholeText,d.id));break;case Bc:g=d.className;break;case Cc:g=e==ic&&h!=jc?ic+": "+h:e==oc?"LINK":e}if(g)return g}return k}
function Hc(a){if(y.ie&&za(a))return"VML Node";if("string"==typeof a)return a;if(a.attributes){var b=a.attributes["data-dtName"];if(b&&b.value)return b.value}b=a.nodeName?a.nodeName.toUpperCase():vc;if(b==rc||b==sc||b==tc||b==qc)return"Page: "+xc;if(b==uc){if(a)if(b=a.nodeName?a.nodeName.toUpperCase():k,b!=uc)a=k;else{var c=Ec(a.id),b=S(c,a.name,b),c=k;a.multiple||(a=a.options&&-1<a.selectedIndex?a.options[a.selectedIndex]:k)&&(c=S(a.label,a.innerText,a.textContent));a=c?"["+b+"] to value ["+c+"]":
b}else a=k;return a}if(b=wa(S(a.innerText,a.textContent)))return b;Dc=0;a:{a=[a];b=Gc;for(c=0;4>=c;c++){var d=b(c,a);if(d){a=d;break a}}a=k}return a}var T,Ic=0,Jc=f,V=s.tdto(),Kc=[[13,"\x3cRETURN\x3e"],[9,"\x3cTAB\x3e"],[8,"\x3cBACKSPACE\x3e"],[127,"\x3cDELETE\x3e"],[27,"\x3cESCAPE\x3e"],[33,"\x3cPAGE UP\x3e"],[34,"\x3cPAGE DOWN\x3e"],[116,"\x3cF5\x3e"]];
function Lc(a,b,c,d){if(s!=V)return V.bi(a,b,c,d);try{var e={id:Ic++,c:a,name:k,type:b,start:m(),A:l,H:m()+(4<=arguments.length?d:30),getName:function(){if(!e.name){var a=Fa(Hc(e.c));a||(a="-");var b=u.sl||100;a.length>b&&(a=a.substring(0,b-3)+"...");e.name=e.type?e.type+' on "'+a+'"':a}return e.name},D:function(){return e.A},G:function(){var a=e;do a.A=f,a=a.next;while(a)}};Jc&&(e.next=T,e.next&&(e.next.j=e),T=e);return e}finally{e&&q(function(){Mc(e)},30)}}
function Vb(){if(s!=V)return V.gci();try{if(T){for(var a=T,b=T.next;b;){var c;if(c=b.c!=a.c)a:{for(var d=b.c.parentNode;d;){if(d==a.c){c=f;break a}d=d.parentNode}c=l}c&&(a=b);b=b.next}return a}return k}catch(e){return k}}function Nc(){for(var a=T;a;)a.c=k,a=a.next;T=k}function Mc(a){if(s!=V)return V.ei(a);if(T){for(var b=T;b.next&&b!==a;)b=b.next;b===a&&(b.c=k,b.j?b.j.next=b.next:T=b.next,b.next&&(b.next.j=b.j))}}
function W(a,b,c){var d=l,e=u.doNotDetect?u.doNotDetect.split(","):k;if(c&&e)for(var h=0;h<e.length;h++)e[h]==c&&(d=f);d||(b||(b=a),B(document,a,function(a){var c=k;a.target?c=a.target:a.srcElement&&(c=a.srcElement);var d=b;if("keypress"==d){a:{a=a.keyCode?a.keyCode:a.charCode;for(var e=0;e<Kc.length;e++)if(Kc[e][0]==a){a=Kc[e][1];break a}e=String.fromCharCode(a);a="a"<=e&&"z">=e||"A"<=e&&"Z">=e||"0"<=e&&"9">=e?e:a}a&&(d+=" "+a)}Lc(c,d,k,30)}))}W("click","click","clk");W("mousedown","mousedown","mdw");
W("mouseup","mouseup","mup");W("dblclick","dblclick","dcl");W("keydown","keypress","kyd");W("keyup","keypress","kyu");W("scroll","scroll","scr");W("touchstart","touch","tcs");W("touchend","touch","tce");if(u.ade){var Oc=u.ade.split(",");if(Oc&&0<Oc.length)for(var Pc=0;Pc<Oc.length;Pc++)W(Oc[Pc])}s.bi=Lc;s.ei=Mc;s.gci=Vb;s.ci=function(){return s!=V?V.ci():Vb()?T.getName():k};s.aad=function(a){(Jc=a)||Nc()};var Qc=l,Rc=l,Sc=l,I=k,Q=k,Tc=Ca("dtSa");Ba("dtSa","-");
if(Tc&&"-"!=Tc){var X=Tc.split("|");if(7==X.length){var Uc={B:"true"==X[0],type:X[1],name:X[2],start:X[3],b:X[4],location:X[5],title:X[6]},Vc=l;s!=s.tdto()&&(Vc=s.tdto().iRO(Uc.location));if(!document.referrer||Uc.location==C(document.referrer)||Uc.location==C(document.location)||Vc)Q=I=Uc}}var Wc=k,Xc=l,Yc=[],Zc=[],$c=l,ad=l,bd=1;s.tdto().aFU(document.location.href);
if(!u.rid){var cd=u.ridPath,dd=cd?cd:n.location.pathname,ed=n.location.search;ed&&0<ed.length&&"?"==ed.charAt(0)&&(ed=ed.substring(1));var fd=ed,Y=1,Y=31*Y+Aa(dd),Y=31*Y+Aa(fd),Y=Y&Y;u.rid="RID_"+Y}var Z=k,gd,hd=Ia();hd&&(Z=hd.timing);function id(){if(Z){var a;a=0<Z.redirectStart?Z.navigationStart+6E4>Z.redirectStart?Z.navigationStart:Z.redirectStart:Z.navigationStart+6E4>Z.fetchStart?Z.navigationStart:Z.fetchStart;return a<aa-2E4||a>aa+2E4?aa:a}return aa}
function jd(){bd--;if(0>=bd){var a=Z?Z.loadEventEnd:0,b;b=Z?Z.loadEventStart:0;b=b<id()?0:b;Wc&&(a&&b?P(Wc.name,a,b):P(Wc.name),Wc=void 0);gd||kd()}}function kd(){ld&&(P(ld.name),ld=k,O())}function md(){Wc||(Wc=Pb("_onload_","_load_",k,ld))}s.sls=function(){};s.sole=jd;s.iolm=function(){bd++};s.solb=md;s.slem=function(){gd=f};s.lst=id;function nd(){if(!Rc){Rc=f;O();for(var a=0;a<Yc.length;a++)try{Yc[a]()}catch(b){}jd()}}function od(){O();Qc||(md(),Qc=f,q(nd,0))}
function pd(){O();Qc||("complete"==document.readyState?Sc?tb(l,f,l):(Sc=f,q(pd,3E3)):q(pd,3E3))}function qd(a,b,c){var d=zb();!d&&a&&b&&c?Ba("dtSa","true|"+C(b)+"|"+C(a)+"|"+c+"|"+D+"|"+C(Ga())+"|"+C(Fa(document.title))):d&&Q?(Ba("dtSa","false|"+Q.type+"|"+Q.name+"|"+m()+"|"+Q.b+"|"+C(Ga())+"|"+C(Fa(document.title))),Q=k):J&&"_load_"!=J.name&&Ba("dtSa","false|"+C(J.type)+"|"+C(J.name)+"|"+m()+"|"+D+"|"+C(Ga())+"|"+C(Fa(document.title)))}function rd(){sd()}
function sd(a){if(!$c){$c=!a;for(a=0;a<Zc.length;a++)Zc[a]($c);ub(l,f,f);(a=Vb())&&a.D()===l?(a.G(),qd(a.getName(),a.type,a.start)):qd(k,k,k);if(y.sf&&n.frames)for(a=0;a<n.frames.length;a++)try{n.frames[a].dT_&&n.frames[a].dT_.obc()}catch(b){}F&&vb(f,l)}}B(n,"beforeunload",rd);
B(n,"unload",function(){sd();if(!ad)try{Nc();var a;for(a=0;a<ya.length;a++){var b=ya[a],c=b.object,d=b.event,e=b.F;y.v&&9>y.v?c.detachEvent("on"+d,e):c.removeEventListener?c.removeEventListener(d,e,l):c.detachEvent&&c.detachEvent("on"+d,e)}Z=ca=ba=ya=k;ad=f}catch(h){}Xc||(Xc=f,Qa())});B(n,"pagehide",function(){sd(f);Xc||(Xc=f,Qa())});B(document,"readystatechange",function(){"loaded"==document.readyState&&O();"complete"==document.readyState&&od()});q(pd,3E3);B(n,"load",od);
(function(){ob||(ob=document.createElement("doc:rdy"));if(ob.doScroll){var a=function(){try{ob.doScroll("left"),ob=k,mb=m(),O()}catch(b){q(a,0)}};a()}else document.addEventListener("DOMContentLoaded",function(){mb=m();O()},l)})();var ld=Pb("_load_","_load_",id(),k);O();s.all=function(a){x(Yc,a)};s.ail=function(a){x(Kb,a)};s.apll=function(a){x(Zc,a)};s.sle=kd;s.obc=rd;s.ile=function(){return 0>=bd};var $=window.dT_,td=[],ud=l;function vd(a){ud?a($.bwsW,$.bwsH):td.push(a)}
$.all(function(){var a=document,b=a.documentElement,c=0,d=0;if("number"==typeof self.innerWidth)c=self.innerWidth,d=self.innerHeight;else if(a&&(b.clientWidth||b.clientHeight))c=b.clientWidth,d=b.clientHeight;else if(a.body&&(a.body.clientWidth||a.body.clientHeight))c=a.body.clientWidth,d=a.body.clientHeight;if(0<c&&0<d)a=screen.availWidth,b=screen.availHeight,c=c<a?c:a,d=d<b?d:b;else{var e;$.gBI().ie?e=140:e=10;c=Math.max(c,e);d=Math.max(d,10)}$.bwsW=c;$.bwsH=d;ud=f;for(a=0;a<td.length;a++)td[a](c,
d)});$.abwsl||($.abwsl=vd);var wd=f;$.asl(function(a,b){if(!b&&wd){wd=l;var c=$.tdto(),d=function(a){return 0>a||2147483647<=a||isNaN(a)?0:a};c?(a.a("w",d(c.bwsW)),a.a("h",d(c.bwsH))):(a.a("w",d($.bwsW)),a.a("h",d($.bwsH)))}});
$.asl(function(){var a=$.gC("dtCookie");if("undefined"!=typeof window.sessionStorage){var b=window.sessionStorage.dtCookie;if("undefined"!=typeof b&&(""!=b&&"null"!=b)&&a!=b){var c;if(c=b){var d=c.indexOf("|");-1!=d&&(c=c.substring(0,d))}"undefined"!=typeof a&&a!=k&&""!=a?a&&c&&(b=a.indexOf("|"),a=-1!=b?c+a.substring(b):c):a=b}a!=k&&($.dC("dtCookie"),$.sC("dtCookie",a),window.sessionStorage.setItem("dtCookie",a))}});
})();(function() {
var c=window.dT_,g=window.performance,k="redirectStart redirectEnd fetchStart domainLookupStart domainLookupEnd connectStart connectEnd secureConnectionStart requestStart responseStart responseEnd domLoading domInteractive domContentLoadedEventStart domContentLoadedEventEnd domComplete loadEventStart loadEventEnd".split(" "),l=!0;
c.smbi("n")&&c.asl(function(d,m){if(!m&&l)if(l=!1,"undefined"!=typeof g)if(c.gBI().ff&&9>=c.gBI().ff)d.a("nt","0");else{var a;a=g.timing||{};var b=g.navigation||{},e=a.navigationStart;if(e){for(var b=["a",b.type,"b",e],n=k.length,f=0;f<n;f++){var h=a[k[f]];h&&h>=e&&(b.push("cdefghijklmnopqrstuvwxyz".charAt(f)),b.push(h-e))}a=b.join("")}else a=null;a?d.a("nt",a):d.a("nt","0")}else d.a("nt","0")});
})();(function() {
var f=window.dT_,k=void 0,l=void 0,m=null,n=null,p={};function q(b){b=m+b.startTime;b-=f.lst();return Math.round(b)}function r(b){f.lst();return Math.round(b.responseEnd)}function s(b){return f.gBI().ch?0!=b.domainLookupStart&&0==b.requestStart:t(b.name)&&0===b.requestStart&&2>b.duration?!0:0>=b.responseEnd?!1:b.requestStart==b.fetchStart&&b.requestStart==b.responseStart&&b.responseStart!=b.responseEnd}
function u(b,g){return b&&b[10]?!1:!t(g.name)&&f.gBI().ie?0!=g.requestStart:b&&"undefined"!==typeof b[7]?b[7]:0<g.responseEnd}function t(b){return f.gh(b)!=f.gh(document.location.href)}
function v(b){for(var g=0;g<b.length;g++){var d=b[g],c=l(d[1]);c&&(t(c.name)||!(f.gBI().ch&&c.domainLookupStart<c.fetchStart))?(p[c.name]=!0,d[5]=q(c),d[11]=Math.round(c.duration),d[6]=0<c.responseEnd?r(c):f.nw(),d[9]=s(c),d[7]=u(d,c),d[8]=0===c.responseEnd):c&&d[7]&&(d[9]=!0,d[8]=!1)}if(k){g=k();for(d=0;d<g.length;d++){var e=g[d];if(!p[e.name]&&(c=e.name,f.tpih(c)&&!(-1<c.indexOf("dtagent"))&&!(-1<c.indexOf("dynaTraceMonitor")))){var c=b,h={};h[0]=w(e);h[11]=Math.round(e.duration);h[5]=q(e);h[6]=
0<e.responseEnd?r(e):f.nw();h[1]=e.name;h[2]=q(e)<=n?"_load_":"-";h[8]=0===e.responseEnd;h[7]=u(null,e);h[9]=s(e);c.push(h)}}}}
function x(){var b=f.gP();if(b&&b.timing){var g=b.getEntriesByType||b.webkitGetEntriesByType,d=b.getEntriesByName||b.webkitGetEntriesByName;g&&d&&(m=b.timing.navigationStart,n=b.timing.loadEventEnd,k=function(){return g.call(b,"resource")},l=function(c){var e=d.call(b,c,"resource");!e&&0<c.indexOf("#")&&(e=d.call(b,c.substring(0,c.indexOf("#")),"resource"));return e[0]},b.onresourcetimingbufferfull=function(){b.setResourceTimingBufferSize(k().length+100)},f.arti=v)}}
function w(b){b=b.name.toLowerCase();-1<b.indexOf("ScriptResource.axd")?b="js":(b=b.substr(1+b.lastIndexOf("/")),0<b.indexOf("?")&&(b=b.split("?")[0]),0<b.indexOf("#")&&(b=b.split("#")[0]),b=0<b.indexOf(".")?b.substring(b.lastIndexOf(".")+1):"-");switch(b){case "js":return"s";case "gif":case "png":case "jpg":case "jpeg":case "ico":case "tiff":case "bmp":case "xbm":case "svg":return"i";case "css":return"y";default:return"o"}}f.smbi("r")&&!window.a&&x();
})();(function() {
var f=!0,k=null,q=!1,r=window.dT_;function s(a,b,e){for(var d=2;d<arguments.length;d++)a.push(arguments[d]),(d<arguments.length-1||b)&&a.push("|")}
function t(){this.head=k;this.add=function(a,b){if(a>b)throw"Error: Start("+a+") must be before stop ("+b+")";var e={start:a,stop:b},d=this.head,g=k;if(d){for(;d&&a>d.start;)g=d,d=d.next;g?(e.next=g.next,g.next=e):(e.next=this.head,this.head=e)}else this.head=e,e.next=k};this.reduce=function(){for(var a=this.head;a&&a.next;){for(;a.next&&a.stop+1>=a.next.start;)a.stop<=a.next.stop&&(a.stop=a.next.stop),a.next=a.next.next;a=a.next}};this.p=function(){this.reduce();for(var a=[],b=this.head;b;)0<a.length&&
s(a,0,"_"),s(a,0,b.start),s(a,0,"_"),s(a,0,b.stop),b=b.next;return a.join("")}}var u=30,v=500,w=3,x=q,y=[],z,A,B,C,D;function E(a,b){for(var e=r.nw(),d=0;d<y.length;d++)if(y[d][1]==b)return;var d=r.ca(),g={};g[0]=a;g[3]=e;g[4]=0;g[1]=b;g[2]=d?d.name:"-";g[9]=q;s(y,0,g)}function F(a,b,e,d){for(var g=0;g<y.length;g++){var m=y[g];if(m[1]==a){2<arguments.length&&0<e&&(m[3]=e);m[4]=3<arguments.length&&0<d?d:r.nw();m[7]=b;b||(m[9]=q,m[10]=f);break}}}
function G(a,b){return a[12]<b[12]?1:a[12]==b[12]?0:-1}function H(){var a=0;r.arti&&r.arti(y);for(a=0;a<y.length;a++){var b=y[a];0===b[4]&&0<b[3]&&("i"===b[0]?(b[8]=f,b[7]=q,b[4]=r.nw()):(b[5]||(b[7]=f),b[4]=b[3]));b[12]=b[4]?b[4]-b[3]:b[12]}}
function I(){var a=r.lst();H();if(0<y.length&&0<a){var b={},e;for(e=0;e<y.length;e++){var d=y[e],g=r.gh(d[1]);b[g]||(b[g]=[]);s(b[g],0,d)}var m={},l=k;for(l in b)if(b.hasOwnProperty(l)&&b[l].length){g=b[l];g.sort(G);var h={};for(e=0;e<g.length;e++){var d=g[e],c=h[d[0]];c||(c={g:0,q:0,n:0,m:0,h:0,j:0,t:new t,v:new t,k:0,e:a+99999999,b:0,l:0,f:a+99999999,d:0},h[d[0]]=c);if(d[3]&&d[4]){c.h++;var n=d[4]-d[3];c.e=c.e<n?c.e:n;c.b=c.b>n?c.b:n;c.k=parseInt((c.k*(c.h-1)+n)/c.h,10);c.t.add(d[3]-a,d[4]-a)}d[5]&&
d[6]&&(c.j++,n=d[11],0>n&&(n=d[6]-d[5]),c.f=c.f<n?c.f:n,c.d=c.d>n?c.d:n,c.l=parseInt((c.l*(c.j-1)+n)/c.j,10),c.v.add(d[5],d[6]));c.g+=d[7]?1:0;c.m+=d[9]?1:0;d[7]||(c.q+=d[8]?1:0,c.n+=d[8]?0:1)}m[l]={u:0};for(var p in h)h.hasOwnProperty(p)&&(c=h[p],m[l].u=Math.max(c.b,c.d),m[l][p]="i"==p||"s"==p?[c.g,c.n,c.q,c.m,c.h,c.j,c.t.p(),c.k,c.h?c.e:"0",c.b,c.v.p(),c.l,c.j?c.f:"0",c.d].join("|"):"o"==p||"y"==p?[c.g,c.n,c.q,c.m,c.v.p(),c.l,c.f,c.d].join("|"):[c.g,c.t.p(),c.k,c.e,c.b].join("|"))}p=[];for(l in m)b.hasOwnProperty(l)&&
s(p,0,l);0<C&&(g=p.sort(function(a,b){return m[b].u-m[a].u}),g.length>C&&(p=g.slice(0,C)));h=[];for(c=0;c<p.length;c++){l=p[c];g=b[l];e=m[l];0<h.length&&s(h,0,";");s(h,1,r.aesc(l),"featureHash");d=0;l=h.length-2;e.i&&(s(h,1,e.i),d+=2);e.s&&(s(h,1,e.s),d+=4);e.y&&(s(h,1,e.y),d+=8);e.o&&(s(h,1,e.o),d+=16);e.c&&(s(h,1,e.c),d+=32);h.pop();h[l]=d.toString(32);for(e=0;e<g.length&&e<w&&(g[e][12]>=v||g[e][11]>=v);e++)d=g[e],s(h,0,","),s(h,0,d[0]+(d[7]?"":d[8]?"i":"f"),d[3]?d[3]-a:0,d[4]?d[4]-a:0,r.aesc(d[2]),
r.aesc(d[1])),d[5]&&s(h,0,"",d[5],d[6])}return r.esc(h.join(""))}return k}function J(a,b){if(!b&&!x){x=f;var e=I();e&&a.a("3p",e);y=[]}}function K(a){var b=r.gh(a);return!(-1!=a.indexOf("chrome-extension://")||-1!=a.indexOf("chrome://")||-1!=a.indexOf("data:"))&&(D||b&&b!=z)}function L(a){F(a.target.src,f)}function M(){window&&window.event&&window.event.srcElement&&("loaded"==window.event.srcElement.readyState||"complete"==window.event.srcElement.readyState)&&F(window.event.srcElement.src,f)}
function N(){for(var a=document.getElementsByTagName("script"),b=0;b<a.length;b++){var e=a[b];if(!e.r&&(e.r=r.nw(),""!=e.src&&K(e.src)&&(!e.attributes||!e.attributes["data-dtconfig"])))E("s",e.src),r.gBI().ie?r.ael(e,"readystatechange",M):r.ael(e,"load",L)}}function O(a){var b=k;a?a.target?b=a.target:a.srcElement&&(b=a.srcElement):window&&window.event&&(b=window.event.srcElement);b&&F(b.src,f)}
function P(a){var b=k;a?a.target?b=a.target:a.srcElement&&(b=a.srcElement):window&&window.event&&(b=window.event.srcElement);b&&b.src!=document.location.href&&F(b.src,q)}function Q(a){if(!a.r){a.r=r.nw();try{""!=a.src&&K(a.src)&&(E("i",a.src),!a.complete||"undefined"!=typeof a.naturalWidth&&0===a.naturalWidth?(r.ael(a,"load",O),r.ael(a,"error",P),a.src=a.src):F(a.src,f))}catch(b){}}}
function R(){var a=document.getElementsByTagName("img"),b,e;for(b=0;b<a.length;b++)e=a[b],Q(e);a=document.getElementsByTagName("input");for(b=0;b<a.length;b++)e=a[b],e.type&&"SUBMIT"==e.type.toUpperCase()&&Q(e)}function S(){0<A&&2E3<r.nw()-A?(B=q,r.asl(J),r.sMPS(5E3)):(R(),N(),r.st(S,u))}var T=r.cfg("tp")?r.cfg("tp"):"500,50,3";
if(r.smbi("3")){var U=T.split(","),V=U.length;3<=V&&5>=V&&(v=parseInt(U[0],10),u=parseInt(U[1],10),w=parseInt(U[2],10),4<=V&&(D=parseInt(U[3],10)),5==V&&(C=parseInt(U[4],10)),z=r.gh(document.location.href),r.apll(function(){r.asl(J)}),r.all(function(){A=r.nw()}),r.asl(function(){-1===A&&(A=r.nw())}),r.tpstr=E,r.tpsto=F,r.tpih=K,R(),N(),r.ca()&&!B&&(A=r.nw(),B=f,S()),A=-1)};
})();